[config]
default_to_workspace = false

[tasks.run-back]
description = "バックエンドの開発サーバーを起動"
script = [
    '''
    export API_PORT=${API_PORT:-8081}
    export STATIC_FILES_PATH=${STATIC_FILES_PATH:-"front/dist"}
    echo "Starting backend server on port $API_PORT"
    cargo run -p webserver
    '''
]

[tasks.run-front]
description = "フロントエンドの開発サーバーを起動"
cwd = "front"
script = [
    '''
    # 環境変数からプロキシURLを取得（デフォルト: http://127.0.0.1:8081/api/）
    PROXY_URL=${PROXY_BACKEND_URL:-http://127.0.0.1:8081/api/}
    echo "Starting frontend with API proxy to $PROXY_URL"
    # Set environment variables for the build process
    export TRUNK_PROFILE=debug
    export TRUNK_DIST_DIR=./dist
    trunk serve --proxy-rewrite=/api/ --proxy-backend=$PROXY_URL
    '''
]

[tasks.build-front]
description = "フロントエンドのビルド"
cwd = "front"
script = [
    '''
    # ビルド時にはプロキシ設定は不要
    echo "Building frontend with optimized TailwindCSS (purged and minified)"
    # Set environment variables for the build process
    export TRUNK_PROFILE=release
    export TRUNK_DIST_DIR=./dist
    # Ensure NODE_ENV is set to production for the entire build process
    export NODE_ENV=production
    trunk build --release --minify
    '''
]

[tasks.build-front2]
description = "フロントエンドのビルド"
cwd = "front"
env = { TRUNK_PROFILE = "release", NODE_ENV = "production" }
script = [
    '''
    echo "Building frontend with optimized TailwindCSS (purged and minified)"

    # 必要なディレクトリを作成
    mkdir -p dist

    # まずTailwindのビルドを実行
    NODE_ENV=production npx tailwindcss -i ./tailwind.css -o ./dist/tailwind.css --minify

    # その後でTrunkビルドを実行
    export TRUNK_PROFILE=release
    trunk build --release
    '''
]

[tasks.build-back]
description = "フロントエンドビルド済み前提でバックエンドをビルド"
script = [
    '''
    export API_PORT=${API_PORT:-8081}
    export STATIC_FILES_PATH=${STATIC_FILES_PATH:-"front/dist"}
    echo "Building backend server for port $API_PORT"
    cargo build -p webserver --release
    '''
]

[tasks.full-release]
description = "フロントエンドとバックエンドの完全リリースビルド"
dependencies = ["build-front", "build-back"]
