[package]
name = "try_leptos"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.8.2", features = ["csr"] }
log = "0.4.27"
console_log = "1.0"
gloo-timers = { version = "0.3.0", features = ["futures"] }
leptos-style = "0.2.0"
