# Trunk 設定ファイル

# エントリーポイントの index.html を指定
build = { target = "index.html" }

# 出力ディレクトリの設定
[output]
dir = "./dist" # ビルド成果物を出力するディレクトリ
create_dir = true # ディレクトリを自動生成

# 静的リソースをコピーする設定
[static]
ignore = [".DS_Store", "Thumbs.db"] # 無視するファイル

# CSS ビンドリングのオプション
[css]
auto_include = true # CSS ファイルを自動的に含める

# Tailwind CSS の設定
[[hooks]]
stage = "build"
command = "sh"
command_arguments = ["./build-tailwind.sh"]
# Pass environment variables to the build hook
[hooks.env]
# Pass the build profile (debug or release) to the script
TRUNK_PROFILE = { value = "${TRUNK_PROFILE}", default = "debug" }
# Pass the output directory to the script
TRUNK_DIST_DIR = { value = "${TRUNK_DIST_DIR}", default = "./dist" }
# Pass the command line arguments to the script
TRUNK_ARGS = { value = "${TRUNK_ARGS}", default = "" }

# サーバーの設定　これは旧記法
#[serve]
#open = true # ビルド後にブラウザを自動で開く
#proxy_backend = "http://localhost:3000" # API サーバーを指定 (バックエンド用)

# プロキシ設定はコマンドラインで指定するため、ここでは設定しない
# 例: trunk serve --proxy api:http://127.0.0.1:8081/api/
