# Trunk 設定ファイル

# エントリーポイントの index.html を指定
build = { target = "index.html" }

# 出力ディレクトリの設定
[output]
dir = "./dist" # ビルド成果物を出力するディレクトリ
create_dir = true # ディレクトリを自動生成

# 静的リソースをコピーする設定
[static]
ignore = [".DS_Store", "Thumbs.db"] # 無視するファイル

# CSS ビンドリングのオプション
[css]
auto_include = true # CSS ファイルを自動的に含める

# サーバーの設定　これは旧記法
#[serve]
#open = true # ビルド後にブラウザを自動で開く
#proxy_backend = "http://localhost:3000" # API サーバーを指定 (バックエンド用)

[[proxies]]
backend = "http://127.0.0.1:3000/" # API サーバーのバックエンド
rewrite = "/api/" # "/api" で始まるリクエストをバックエンドにプロキシ    {tail}などは非対応(設定不要、不能？)
